server:
  port: 8888  # Default port for Config Server

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Myriem1/ecommerce-config-repo.git  # URI of your dedicated config repo
          clone-on-start: true  # Clone the repo on startup for faster access
          force-pull: true      # Always pull the latest changes
          timeout: 10           # Connection timeout in seconds

management:  # Optional: Expose endpoints for monitoring
  endpoints:
    web:
      exposure:
        include: health,info,refresh